export enum PracticeLane {
  QUICK_ROUNDS = "QUICK_ROUNDS",
  ENCOUNTERS = "ENCOUNTERS",
  GROUP_CHAT_LAB = "GROUP_CHAT_LAB",
  SKILL_DRILLS = "SKILL_DRILLS",
}
export enum ConversationRole {
  USER = "USER",
  ACTOR = "ACTOR",
}
export enum Difficulty {
  GENTLE = "GENTLE",
  REALISTIC = "REALISTIC",
  CHALLENGE = "CHALLENGE",
  DIFFICULT = "DIFFICULT",
}
export enum EncounterStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ABANDONED = "ABANDONED",
}
export enum HelperId {
  TONE_SPECTRUM = "TONE_SPECTRUM",
  X_RAY = "X_RAY",
  REPHRASER = "REPHRASER",
  RESPONSE_BUILDER = "RESPONSE_BUILDER",
  CUE_DETECTOR = "CUE_DETECTOR",
}

export enum SocialSkill {
  EMPATHY = "EMPATHY",
  ASSERTIVENESS = "ASSERTIVENESS",
  CLARITY = "CLARITY",
  ENGAGEMENT = "ENGAGEMENT",
  SOCIAL_AWARENESS = "SOCIAL_AWARENESS",
  SETTING_BOUNDARIES = "SETTING_BOUNDARIES",
  REPAIR = "REPAIR",
  CUE_RECOGNITION = "CUE_RECOGNITION",
  SMALL_TALK = "SMALL_TALK",
  CONFLICT_NAVIGATION = "CONFLICT_NAVIGATION",
  EMOTIONAL_RECOGNITION = "EMOTIONAL_RECOGNITION",
  RELEVANCE = "RELEVANCE",
  TONE_AWARENESS = "TONE_AWARENESS",
  FOLLOW_UP = "FOLLOW_UP",
  CONVERSATION_FLOW = "CONVERSATION_FLOW",
  SOCIAL_TIMING = "SOCIAL_TIMING",
  PERSPECTIVE_TAKING = "PERSPECTIVE_TAKING",
}

/** Aggregated skill scores for an encounter */
export type ScoreSummary = Partial<Record<SocialSkill, number>>;
